/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

interface Category {
  title: string;
  description: string;
  id: number;
}
interface Nodes {
  title: string;
  description: string;
  id: number;
  categories: Category[];
}
export default function Home({ nodes }) {
  return (
    <>
      <Head>
        <title>zForum</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container md:w-[70%] mx-auto">
        <div className="bg-slate-600 p-3 rounded-lg flex flex-col lg:flex-row justify-between">
          <div className="lg:w-[70%]">
            {nodes.map((node: Nodes) => (
              <div
                key={node.id}
                className="bg-slate-700 pb-[1px] mt-2 rounded-md m-[1px]"
              >
                <div className="bg-gray-800 text-white rounded-t-md p-2">
                  <div className="flex justify-between">
                    <div className="flex flex-col items-center justify-center mx-auto">
                      <div className="text-lg font-bold uppercase">{node.title}</div>
                      <span className="text-sm">{node.description}</span>
                    </div>
                  </div>
                </div>
                {node.categories.map((category) => (
                  <div
                    key={category.id}
                    className="bg-gray-300 hover:shadow-md shadow-white m-2 rounded-lg p-[6px] flex flex-row gap-2 items-center border-slate-200 border-[1px]"
                  >
                    <div className="flex flex-col">
                      <div className="">{category.title}</div>
                      <span>{category.description}</span>
                    </div>
                    <div className="flex flex-col items-center w-[30%]">
                      <div className="bg-black text-white rounded-lg pr-2 p-1 pl-2">
                        Topics
                      </div>
                      <span className="rounded-full bg-indigo-600 pr-1 pl-1 mt-[-0.5rem] ml-[3.4rem] absolute">12</span>
                    </div>
                    <div className="flex flex-row gap-2 items-center ml-auto">
                      <img
                        src="https://ui-avatars.com/api/?name=zRooter&background=random"
                        alt="profile"
                        className="rounded-2xl hover:rounded-full hover:duration-500 ease-in-out"
                      />
                      <div className="flex flex-col">
                        <div className="text-xl font-semibold">zRooter</div>
                        <span className="text-sm">4.01.2023 16:41</span>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            ))}
          </div>
          <div className="lg:w-[30%]">
            <div className="bg-gray-300 hover:shadow-md shadow-white m-2 rounded-lg p-2 border-slate-200 border-[1px]">
              <div className="">
                <div className="text-xl font-bold text-center uppercase">
                  User Data
                </div>
              </div>

              <div className="flex flex-col">
                <div className="flex gap-2 items-center">
                  <img
                    src="https://ui-avatars.com/api/?name=zRooter&background=random"
                    alt="profile"
                    className="rounded-2xl hover:rounded-full hover:duration-500 ease-in-out"
                  />
                  <div className="flex flex-col">
                    <span className="text-xl font-semibold">zRooter</span>
                    <div className="flex flex-wrap gap-2">
                      <div className="bg-red-500 rounded-lg text-white pl-2 pr-2">
                        Owner
                      </div>
                      <div className="bg-indigo-500 rounded-lg text-white pl-2 pr-2">
                        Team
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
export async function getStaticProps() {
  const res = await fetch("http://localhost:3000/api/nodes", {
    headers: {
      Accept: "application/json",
    },
  });
  const data: Nodes[] = await res.json();
  return {
    props: {
      nodes: data,
    },
  };
}
